# Generated by Django 6.0.5 on 2026-05-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='commercial_register_file',
            field=models.FileField(blank=True, null=True, upload_to='commercial_registers/'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='license_file',
            field=models.FileField(blank=True, null=True, upload_to='provider_licenses/'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='professional_license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
