# Generated by Django 6.0.5 on 2026-05-16 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_booking_customer_name_booking_customer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='rating',
        ),
    ]
