# Generated by Django 5.2.6 on 2026-06-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_remove_serviceprovider_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('commercial_register_number', models.CharField(blank=True, max_length=100)),
                ('tax_number', models.CharField(blank=True, max_length=100)),
                ('professional_license_number', models.CharField(blank=True, max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='provider_applications/profile/')),
                ('license_file', models.FileField(blank=True, null=True, upload_to='provider_applications/licenses/')),
                ('commercial_register_file', models.FileField(blank=True, null=True, upload_to='provider_applications/registers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
